apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namePrefix: agent-message-bus-

labels:
  - pairs:
      app: agent-message-bus
    includeSelectors: true

configMapGenerator:
  - name: tool-code
    files:
      - index.mjs
      - package.json