apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: deepseek-proxy
resources:
  - ../../base

labels:
  - pairs:
      app: deepseek-proxy
    includeSelectors: true

generatorOptions: {}

configMapGenerator:
  - name: proxy-code
    files:
      - index.mjs
      - package.json

patches:
  - target:
      kind: Deployment
      name: proxy
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: API_KEY
          valueFrom:
            secretKeyRef:
              name: openclaw-secrets
              key: DEEPSEEK_API_KEY
              optional: false
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: UPSTREAM_BASE_URL
          value: "https://api.deepseek.com"
