apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coder-agent
resources:
  - namespace.yaml
  - ../../base
  - ../../../tools/overlays/telegram

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: openclaw-workspace
    files:
      - workspace/AGENTS.md
      - workspace/LEARNINGS.md
      - workspace/HEARTBEAT.md
      - workspace/IDENTITY.md
      - workspace/SOUL.md
      - workspace/TOOLS.md
      - workspace/USER.md