apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - k8s/agents/overlays/coder
 - k8s/agents/overlays/reviewer
 - k8s/agents/overlays/security
 - k8s/proxies/overlays/deepseek
 - k8s/proxies/overlays/openai
 - k8s/rbac
