apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openai-proxy
resources:
  - namespace.yaml
  - ../../base

namePrefix: openai-
labels:
  - pairs:
      app: openai-api-proxy
    includeSelectors: true

generatorOptions: {}

configMapGenerator:
  - name: proxy-code
    files:
      - index.mjs
      - package.json
