apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - path: patches/add-api-key-env.yaml

namePrefix: deepseek-mcp-
labels:
  - pairs:
      app: deepseek-mcp-service
    includeSelectors: true

generatorOptions: {}

configMapGenerator:
  - name: tool-code
    files:
      - index.mjs
      - package.json
